db:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=ZULAv8in
app:
  image: piwik
  links:
    - db
  volumes:
    - /opt/compose/piwikazv/config:/var/www/html/config
web:
  image: nginx
  volumes:
    - /opt/compose/piwikazv/nginx.conf:/etc/nginx/nginx.conf
  links:
    - app
    - db
  volumes_from:
    - app
  ports:
    - 81:80
    - 3306:3306
