db:
  image: mysql
  environment:
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
app:
  image: piwik
  links:
    - db
  volumes:
    - ./config:/var/www/html/config
web:
  image: nginx
  ports:
    - "10080:80"
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  links:
    - app
  volumes_from:
    - app
