db:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=xxxxx
app:
  image: piwik
  links:
    - db
  volumes:
    - /opt/compose/piwik/config:/var/www/html/config
web:
  image: nginx
  volumes:
    - /opt/compose/piwik/nginx.conf:/etc/nginx/nginx.conf
  links:
    - app
  volumes_from:
    - app
  ports:
    - 81:80
